Repository Workiva/barometer, pull requests merged in 2019-04, with the labels that each got.

#1 Initial Commit to OpenSource Repository
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  LICENSE
  Makefile
  NOTICE
  README.md
  aviary.yaml
  documentation/barometer.aspects.html
  documentation/barometer.core.html
  documentation/barometer.protocols.html
  documentation/css/default.css
  documentation/css/highlight.css
  documentation/index.html
  documentation/js/highlight.min.js
  documentation/js/jquery.min.js
  documentation/js/page_effects.js
  project.clj
  src/barometer/aspects.clj
  src/barometer/core.clj
  src/barometer/protocols.clj
  workivabuild.Dockerfile
Labels: InfoSec Review Required, Merge Requirements Unmet

#2 EVA-981 Add CircleCI to barometer
  .circleci/clojars/profiles.clj
  .circleci/config.yml
  .circleci/scripts/update-tocs.sh
  .circleci/scripts/verify-dockerfile.sh
  .circleci/scripts/verify-docs.sh
  .circleci/scripts/verify-license-headers.sh
  .gitattributes
  .gitignore
  Makefile
  README.md
  documentation/barometer.aspects.html
  documentation/barometer.core.html
  documentation/barometer.protocols.html
  documentation/css/default.css
  documentation/css/highlight.css
  documentation/highlight/highlight.min.js
  documentation/highlight/solarized-light.css
  documentation/index.html
  documentation/js/page_effects.js
  package.json
  project.clj
  src/barometer/core.clj
  workivabuild.Dockerfile
Labels: Merge Requirements Met, RM Ready

#4 RM-48624 Release barometer v0.1.0
  project.clj
Labels: Merge Requirements Met, RM Ready

#6 Bump dependency recide 1.0.0 -> 1.0.1
  project.clj
Labels: Merge Requirements Met, RM Ready

#7 RM-48625 Release barometer v0.1.1
  project.clj
Labels: Merge Requirements Met, RM Ready

#8 Updating morphe dependency to latest and greatest
  project.clj
Labels: Merge Requirements Met

#5 EVA-982 Add Github Pages documentation to barometer
  .circleci/config.yml
  Gemfile
  Makefile
  README.md
  _config.yml
  assets/css/style.scss
Labels: Merge Requirements Met, RM Ready

#9 RM-48863 Release barometer v0.1.2
  project.clj
Labels: Merge Requirements Met, RM Ready
